### PR TITLE
Cleanup of formatting, require statements and keeping lines to 80 characters

### PR DESCRIPTION
**Pull request by nbeyer**
Most of this is general code cleanup of the format, but there are some opinionated bits in here, which may or may not be desirable:
- Refactoring of the 'require' statements, such that only the direct dependencies of each file are declared, rather than dumping everything into 'gc_stats.rb'
- Added some code comments to give a bit more information about intent

### CODE REVIEW

**Comment by faizahmedshaik** [comment]
+1, especially for the refactoring of the require statements. We've had a couple of engines yesterday give a 'uninitialized constant GCStats::Middleware' error when running specs due to the order of the requires.

**Comment by kpshek** [comment]
:+1: 

Thanks, @nbeyer

**Comment by kpshek** [comment]
@nbeyer - Can you update this PR based on 2a506c152d (the merge of #1) so that we'll have a clean merge for these changes?

**Comment by nbeyer** [comment]
I've updated the pull request. It should be based on the latest master commits. I've also updated the changelog and set the version to 1.0.1.

**Comment by kpshek** [comment]
Thanks for updating the pull request and the CHANGELOG.md. What do you think about linking back to these issues (#1 and #2) for each item?

**Comment by nbeyer** [comment]
Yeah, I'm fine with whatever format is desired. Do you have a format suggestion? I can rework that and post another update.

**Comment by nbeyer** [comment]
@kpshek Check the latest update to the PR; I updated the CHANGELOG.md to use the title of the PRs and made them links to the PRs.

**Comment by kpshek** [comment]
@nbeyer Looks great. Thanks again.

**Pull request merged**
